# Generated by Django 5.1.4 on 2025-05-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_userapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveQueryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('website_link', models.CharField(blank=True, max_length=100, null=True)),
                ('query', models.TextField()),
                ('budget', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
